---
- name: Install virtualization package group
  dnf: name="@virtualization" state=present
  sudo: True
- name: Install Vagrant (with libvirt support)
  dnf: name={{ item }} state=present
  with_items:
      - libvirt-devel
      - vagrant
      - vagrant-libvirt
- name: Add VirtualBox repository
  get_url: url=http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo dest=/etc/yum.repos.d
  sudo: True
- name: Install VirtualBox
  dnf: name={{ item }} state=present
  with_items:
      - kernel-headers
      - kernel-devel
      - dkms
      - VirtualBox-4.3
- name: Configure VirtualBox kernel module
  command: /etc/init.d/vboxdrv setup
  sudo: True
- name: Clone virtualbox-utils repository
  git: repo=ssh://git@github.com/nihilifer/virtualbox-utils.git dest=~/virtualbox-utils
  ignore_errors: True
- name: Install virtualbox-utils
  pip: name=~/virtualbox-utils virtualenv=~/.virtualenvs/virtualbox extra_args='-e'
- name: Install VirtualBox Extension Pack
  command: vbox-utils-extpack
  environment:
      PATH: "{{ ansible_env.HOME }}/.virtualenvs/virtualbox/bin:{{ ansible_env.PATH }}"
